-- ============================================================
-- Oracle XE 21c — Sede Central (Administrativo)
-- TecnoChapina S.A.
-- PASO 2: Ejecutar como admin_central / AdminPass123
-- ============================================================

-- Tablas en el tablespace ts_central

CREATE TABLE empleados (
  id_empleado        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre             VARCHAR2(100) NOT NULL,
  apellido           VARCHAR2(100) NOT NULL,
  email              VARCHAR2(150),
  telefono           VARCHAR2(20),
  puesto             VARCHAR2(80),
  sede               VARCHAR2(20) CHECK (sede IN ('Central', 'Occidente', 'Capital')),
  id_supervisor      NUMBER,
  fecha_contratacion DATE,
  CONSTRAINT fk_supervisor FOREIGN KEY (id_supervisor)
    REFERENCES empleados(id_empleado) DEFERRABLE INITIALLY IMMEDIATE
) TABLESPACE ts_central;

COMMENT ON COLUMN empleados.sede         IS 'Central | Occidente | Capital';
COMMENT ON COLUMN empleados.id_supervisor IS 'Auto-referencia: jefe directo del empleado';

-- ----

CREATE TABLE proveedores (
  id_proveedor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre       VARCHAR2(150) NOT NULL,
  contacto     VARCHAR2(100),
  email        VARCHAR2(150),
  telefono     VARCHAR2(20),
  pais         VARCHAR2(60)
) TABLESPACE ts_central;

-- ----

CREATE TABLE auditoria (
  id_auditoria   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tabla_afectada VARCHAR2(60),
  operacion      VARCHAR2(10) CHECK (operacion IN ('INSERT', 'UPDATE', 'DELETE')),
  id_registro    NUMBER,
  usuario_db     VARCHAR2(60),
  fecha_hora     TIMESTAMP DEFAULT SYSTIMESTAMP,
  detalle        VARCHAR2(500)
) TABLESPACE ts_central;

COMMENT ON TABLE  auditoria           IS 'Registro generico de operaciones — sin FK por diseno';
COMMENT ON COLUMN auditoria.operacion IS 'INSERT | UPDATE | DELETE';
