CREATE TABLE "empleados" (
  "id_empleado" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "apellido" varchar(100) NOT NULL,
  "email" varchar(150),
  "telefono" varchar(20),
  "puesto" varchar(80),
  "sede" varchar(20),
  "id_supervisor" integer,
  "fecha_contratacion" date
);

CREATE TABLE "proveedores" (
  "id_proveedor" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150) NOT NULL,
  "contacto" varchar(100),
  "email" varchar(150),
  "telefono" varchar(20),
  "pais" varchar(60)
);

CREATE TABLE "auditoria" (
  "id_auditoria" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tabla_afectada" varchar(60),
  "operacion" varchar(10),
  "id_registro" integer,
  "usuario_db" varchar(60),
  "fecha_hora" timestamp,
  "detalle" varchar(500)
);

CREATE TABLE "categorias" (
  "id_categoria" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(80) NOT NULL,
  "descripcion" varchar(300)
);

CREATE TABLE "productos" (
  "id_producto" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150) NOT NULL,
  "descripcion" varchar(500),
  "precio_unitario" decimal(10,2),
  "id_categoria" integer NOT NULL,
  "id_proveedor" integer
);

CREATE TABLE "inventario" (
  "id_inventario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" integer NOT NULL,
  "bodega" varchar(60),
  "cantidad_disponible" integer DEFAULT 0,
  "fecha_actualizacion" timestamp
);

CREATE TABLE "clientes" (
  "id_cliente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "apellido" varchar(100) NOT NULL,
  "email" varchar(150),
  "telefono" varchar(20),
  "direccion" varchar(250),
  "nit" varchar(20)
);

CREATE TABLE "ventas" (
  "id_venta" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_cliente" integer NOT NULL,
  "id_empleado" integer,
  "fecha_venta" timestamp,
  "total" decimal(12,2),
  "sucursal_id" integer,
  "estado" varchar(20)
);

CREATE TABLE "detalle_ventas" (
  "id_detalle" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_venta" integer NOT NULL,
  "id_producto" integer,
  "cantidad" integer,
  "precio_unitario" decimal(10,2),
  "subtotal" decimal(12,2)
);

COMMENT ON COLUMN "empleados"."sede" IS 'Central | Occidente | Capital';

COMMENT ON COLUMN "empleados"."id_supervisor" IS 'Ref. lógica → empleados';

COMMENT ON COLUMN "auditoria"."operacion" IS 'INSERT | UPDATE | DELETE';

COMMENT ON COLUMN "productos"."id_proveedor" IS 'Ref. lógica → Oracle.proveedores';

COMMENT ON COLUMN "ventas"."id_empleado" IS 'Ref. lógica → Oracle.empleados';

COMMENT ON COLUMN "ventas"."sucursal_id" IS '1=Capital | 2=Occidente (fragmentacion horizontal)';

COMMENT ON COLUMN "ventas"."estado" IS 'completada | anulada';

COMMENT ON COLUMN "detalle_ventas"."id_producto" IS 'Ref. lógica → PostgreSQL.productos';

ALTER TABLE "empleados" ADD FOREIGN KEY ("id_supervisor") REFERENCES "empleados" ("id_empleado") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "productos" ADD FOREIGN KEY ("id_categoria") REFERENCES "categorias" ("id_categoria") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventario" ADD FOREIGN KEY ("id_producto") REFERENCES "productos" ("id_producto") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ventas" ADD FOREIGN KEY ("id_cliente") REFERENCES "clientes" ("id_cliente") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detalle_ventas" ADD FOREIGN KEY ("id_venta") REFERENCES "ventas" ("id_venta") DEFERRABLE INITIALLY IMMEDIATE;
